### PR TITLE
I tried to fix #314

### LINKED ISSUE #314: Invalid argument when throwing exception for unknown namespace:
The namespace collection can be an `ArrayObject`, in which case `array_keys` does not work, causing an error to be produced when an exception should be thrown in the `NodeProcessor`:

```
        if (!isset($this->namespaces[$alias])) {
            throw new NamespaceException(sprintf(
                'Namespace alias "%s" is not known for name "%s", known namespace aliases are: "%s"',
                $alias,
                $name,
                implode('", "', array_keys($this->namespaces))
            ));
        }
    }
```

### PR DESCRIPTION
**Pull request by vondrasekpavel**
I must update phpDoc in Jackalope-Doctrine-Dbal Client after merge :)

### CODE REVIEW

File: src/Jackalope/NodeType/NodeProcessor.php [hunk 1]
```diff
@@ -343,19 +344,23 @@ private function validateNamespace($name)
     {
         $alias = null;
         $aliasLength = strpos($name, ':');
-        if (false === $aliasLength) {
+
+        if ($aliasLength === false) {
```
Comment (dbu) [inline src/Jackalope/NodeType/NodeProcessor.php]: its a best practice to have the constant value on the left side and the variable right, to avoid accidentally assigning values. please revert this line

File: src/Jackalope/NodeType/NodeProcessor.php [hunk 2]
```diff
@@ -71,18 +72,18 @@ class NodeProcessor
...
-     * @param array   $namespaces       List of namespaces in the current session. Keys are prefix, values are URI.
-     * @param boolean $autoLastModified Whether the last modified property should be updated automatically
+     * @param string      $userId           ID of the connected user
+     * @param ArrayObject $namespaces       List of namespaces in the current session. Keys are prefix, values are URI.
+     * @param bool        $autoLastModified Whether the last modified property should be updated automatically
      */
     public function __construct(
         $userId,
-        $namespaces = array(),
+        ArrayObject $namespaces,
```
Comment (dbu) [inline src/Jackalope/NodeType/NodeProcessor.php]: this makes $namespaces not optional anymore. but you verified usage of NodeProcessor and the namespaces are always passed in?

File: src/Jackalope/NodeType/NodeProcessor.php [hunk 3]
```diff
@@ -343,19 +344,23 @@ private function validateNamespace($name)
...
         $alias = null;
         $aliasLength = strpos($name, ':');
-        if (false === $aliasLength) {
+
+        if ($aliasLength === false) {
             return;
-        } 
-        
-        $alias = substr($name, 0, $aliasLength);
+        } else {
```
Comment (dbu) [inline src/Jackalope/NodeType/NodeProcessor.php]: no need for an else. when the `if` is entered, we return. not having the else makes the code more readable as you see that we either already stopped, or we get to this line.

File: src/Jackalope/NodeType/NodeProcessor.php [hunk 4]
```diff
@@ -343,19 +344,23 @@ private function validateNamespace($name)
...
+        }
 
         if (!isset($this->namespaces[$alias])) {
-            throw new NamespaceException(sprintf(
-                'Namespace alias "%s" is not known for name "%s", known namespace aliases are: "%s"',
-                $alias,
-                $name,
-                implode('", "', array_keys($this->namespaces))
-            ));
+            if ($this->namespaces instanceof ArrayObject) {
```
Comment (dbu) [inline src/Jackalope/NodeType/NodeProcessor.php]: can this ever not be true now? when we force ArrayObject and its not optional, i think we need no check.

File: src/Jackalope/NodeType/NodeProcessor.php [hunk 5]
```diff
@@ -343,19 +344,23 @@ private function validateNamespace($name)
...
+                $this->namespaces = $this->namespaces->getArrayCopy();
```
Comment (dbu) [inline src/Jackalope/NodeType/NodeProcessor.php]: this is dangerous, as it breaks the binding with the ArrayObject. after such an error, the behaviour will change.

i would do: `$aliases = implode("', '", array_keys($this->namespaces->getArrayCopy());`

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 1 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: OK :)

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 4 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: Sorry I forgot :(

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 5 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: Yes, I thought over this line... but I wanted to know your feedback :) I will update it :)

**Comment by vondrasekpavel** [comment]
snimek obrazovky 2017-01-20 v 14 50 21

I tested it with Doctrine Dbal (I copied it to vendor) and all test worked.

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 2 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: I tried to search where is NodeProcessor used and I think that is actually only in Jackalope Doctrine Dbal Client and NodeProcessorTest:

snimek obrazovky 2017-01-20 v 14 54 46

And there aren't namespaces optional so I don't know...

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 1 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: Ok

File: src/Jackalope/NodeType/NodeProcessor.php (hunk 3 above)
Comment (vondrasekpavel) [inline src/Jackalope/NodeType/NodeProcessor.php]: Yes, you're right I will fix it :)

**Comment by dbu** [comment]
great, thanks a lot!

**Comment by vondrasekpavel** [comment]
I thank you too! :)
